### ISSUE TITLE
Add docker-compose example to readme

### ISSUE THREAD

**Issue by TonyBrobston** [TonyBrobston/logs-to-mqtt-publisher#38]
```
version: '3'
  
services:
    home-assistant:
        image: homeassistant/home-assistant
        ports:
            - 8123:8123

    mqtt-broker:
        image: eclipse-mosquitto

    log-to-mqtt-publisher:
        build:
            context: logs-to-mqtt-publisher/.
        volumes:
            - /var/log/unifi-video:/private/var/log/unifi-video
        environment:
            - OPTIONS={"log":true,"logWatches":[{"filePath":"/var/log/unifi-video/motion.log","logParses":[{"topicParse":{"regularExpression":"/motion|House West/g","order":[0,1],"delimiter":"/"},"message
```
