### ISSUE TITLE
Add json support for options

### ISSUE THREAD

**Issue by TonyBrobston** [TonyBrobston/logs-to-mqtt-publisher#48]
Currently you must pass in a JavaScript object directly to the function or set it through an environment variable (`OPTIONS`). It should be possible to support json.

**Comment by TonyBrobston** [comment]
docker-compose.yml:
```
version: '3'

services:
    home-assistant:
        image: homeassistant/home-assistant
        ports:
            - 8123:8123

    mqtt-broker:
        image: eclipse-mosquitto

    logs-to-mqtt-publisher:
        build:
            context: logs-to-mqtt-publisher/.
        volumes:
            - /Users/tonybrobston/Projects:/var/log/unifi-video
        environment:
            - OPTIONS_FILE_PATH=/var/log/unifi-video/options.json
```

options.json:
```
{
   "log":true,
   "logWatches":[
      {
         "filePath":"/var/log/unifi-video/motion.log",
         "logParses":[
            {
               "topicParse":{
                  "regularExpression":"/motion|House West/g",
                  "output":"{0}/{1}"
               },
               "messageParse":{
                  "regularExpression":"/start/g",
                  "output":"{0}"
               }
            }
         ]
      }
   ],
   "mqtt":{
      "host":"mqtt-broker",
      "port":"1883"
   }
}
```
